"use client";

import { useState } from "react";
import { useAppStore } from "@/components/layout/app-store";
import { Button, Card, Field, inputClass } from "@/components/ui/primitives";
import { todayInPoland } from "@/lib/date";

export function GrowthInputs() {
  const { data, upsertGrowthExperiment, upsertInvestmentModel, addMeterReading } = useAppStore();
  const unitId = data.units[0]?.id ?? "";
  const [experiment,setExperiment]=useState({name:"Pakiet wędkarski poza sezonem",dateFrom:todayInPoland(),dateTo:todayInPoland(),cost:"",code:"",criterion:""});
  const [investment,setInvestment]=useState({unitId,initial:"",capex:"",withdrawals:"",shared:"",source:""});
  const [meter,setMeter]=useState({unitId,meterId:"prąd",value:"",source:"odczyt ręczny",photoUrl:""});
  const number=(value:string)=>Number(value.replace(",","."));

  return <Card className="overflow-hidden"><header className="border-b border-[#e2dbce] p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Kontrolowane dane wejściowe</p><h3 className="font-display text-2xl font-semibold">Eksperyment, payback i licznik</h3></header><div className="grid gap-px bg-[#e5ded2] lg:grid-cols-3">
    <form className="grid content-start gap-3 bg-[#fffdf8] p-5" onSubmit={(event)=>{event.preventDefault();upsertGrowthExperiment({id:`EXP-${Date.now()}`,name:experiment.name,dateFrom:experiment.dateFrom,dateTo:experiment.dateTo,cost:number(experiment.cost),currency:"PLN",code:experiment.code,successCriterion:experiment.criterion,decision:"planned"});}}><p className="text-sm font-black">Eksperyment ofertowy</p><Field label="Nazwa"><input className={inputClass} required value={experiment.name} onChange={(event)=>setExperiment({...experiment,name:event.target.value})}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Od"><input className={inputClass} required type="date" value={experiment.dateFrom} onChange={(event)=>setExperiment({...experiment,dateFrom:event.target.value})}/></Field><Field label="Do"><input className={inputClass} required type="date" value={experiment.dateTo} onChange={(event)=>setExperiment({...experiment,dateTo:event.target.value})}/></Field></div><Field label="Koszt PLN"><input className={inputClass} min="0" required type="number" value={experiment.cost} onChange={(event)=>setExperiment({...experiment,cost:event.target.value})}/></Field><Field label="Kod"><input className={inputClass} required value={experiment.code} onChange={(event)=>setExperiment({...experiment,code:event.target.value})}/></Field><Field label="Kryterium sukcesu"><textarea className={`${inputClass} min-h-20`} required value={experiment.criterion} onChange={(event)=>setExperiment({...experiment,criterion:event.target.value})}/></Field><Button type="submit">Zapisz plan eksperymentu</Button></form>
    <form className="grid content-start gap-3 bg-[#fffdf8] p-5" onSubmit={(event)=>{event.preventDefault();upsertInvestmentModel({id:`INVEST-${investment.unitId}-PLN`,unitId:investment.unitId,initialCapital:number(investment.initial),additionalCapex:number(investment.capex),ownerWithdrawals:number(investment.withdrawals),sharedCostAllocation:number(investment.shared),currency:"PLN",source:investment.source});}}><p className="text-sm font-black">Model payback</p><Field label="Domek"><select className={inputClass} required value={investment.unitId} onChange={(event)=>setInvestment({...investment,unitId:event.target.value})}>{data.units.map((unit)=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></Field>{[["initial","Kapitał początkowy"],["capex","Dodatkowe nakłady"],["withdrawals","Wypłaty właściciela"],["shared","Koszty wspólne"]].map(([key,label])=><Field key={key} label={`${label} PLN`}><input className={inputClass} min="0" required type="number" value={investment[key as keyof typeof investment]} onChange={(event)=>setInvestment({...investment,[key]:event.target.value})}/></Field>)}<Field label="Źródło / podstawa"><input className={inputClass} required value={investment.source} onChange={(event)=>setInvestment({...investment,source:event.target.value})}/></Field><Button type="submit">Zapisz założenia payback</Button></form>
    <form className="grid content-start gap-3 bg-[#fffdf8] p-5" onSubmit={(event)=>{event.preventDefault();addMeterReading({id:`METER-${Date.now()}`,unitId:meter.unitId,meterId:meter.meterId,recordedAt:new Date().toISOString(),value:number(meter.value),unit:"kWh",source:meter.source,photoUrl:meter.photoUrl||undefined,recordedBy:"Użytkownik aplikacji"});setMeter({...meter,value:"",photoUrl:""});}}><p className="text-sm font-black">Ręczny odczyt prądu</p><Field label="Domek"><select className={inputClass} required value={meter.unitId} onChange={(event)=>setMeter({...meter,unitId:event.target.value})}>{data.units.map((unit)=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></Field><Field label="Licznik"><input className={inputClass} required value={meter.meterId} onChange={(event)=>setMeter({...meter,meterId:event.target.value})}/></Field><Field label="Stan kWh"><input className={inputClass} min="0" required step=".01" type="number" value={meter.value} onChange={(event)=>setMeter({...meter,value:event.target.value})}/></Field><Field label="Źródło"><input className={inputClass} required value={meter.source} onChange={(event)=>setMeter({...meter,source:event.target.value})}/></Field><Field label="URL zdjęcia (opcjonalnie)"><input className={inputClass} type="url" value={meter.photoUrl} onChange={(event)=>setMeter({...meter,photoUrl:event.target.value})}/></Field><Button type="submit">Zapisz odczyt</Button><p className="text-[10px] leading-4 text-[#737d77]">API licznika pozostaje poza zakresem do czasu oceny wartości ręcznego pilota.</p></form>
  </div></Card>;
}
