import type { AppData, Booking, Unit } from "./types";

export const units: Unit[] = [
  {
    id: "domek-rybaka",
    name: "Domek Rybaka",
    maxPeople: 6,
    bedrooms: 3,
    defaultPricePerNight: 650,
    defaultCleaningCost: 250,
    notes: "Większy domek, mocny dla rodzin i wędkarzy.",
  },
  {
    id: "domek-4",
    name: "Czapla",
    maxPeople: 4,
    bedrooms: 2,
    defaultPricePerNight: 500,
    defaultCleaningCost: 220,
    notes: "Mniejszy domek, para albo rodzina 2+2.",
  },
];

export const sampleBookings: Booking[] = [
  {
    id: "G001",
    bookingDate: "2026-07-02",
    source: "Rozmowa na miejscu",
    platform: "Booking",
    platformReservationNo: "BKG-19284",
    unitId: "domek-rybaka",
    checkIn: "2026-07-10",
    checkOut: "2026-07-17",
    adults: 2,
    children: 2,
    guestLabel: "Rodzina z okolic Gdańska",
    cityArea: "okolice Gdańska",
    grossPrice: 4550,
    currency: "PLN",
    paymentStatus: "Opłacone",
    openingPaidAmount: 4550,
    openingPaidCurrency: "PLN",
    openingPaidSource: "Dane demonstracyjne · saldo migracyjne",
    workflowStatus: "W trakcie",
    specialRequests:
      "Synowie chcieli na ryby. Najpierw prawdopodobnie AI/czat, potem potwierdzenie na Booking.",
    createdBy: "Import Booking + Patryk",
  },
  {
    id: "G002",
    bookingDate: "2026-07-10",
    source: "Telefon",
    platform: "Bezpośrednio",
    unitId: "domek-4",
    checkIn: "2026-07-18",
    checkOut: "2026-07-21",
    adults: 2,
    children: 1,
    guestLabel: "Para z dzieckiem - roboczo",
    cityArea: "Trójmiasto",
    grossPrice: 1350,
    depositAmount: 300,
    currency: "PLN",
    paymentStatus: "Zaliczka",
    openingPaidAmount: 300,
    openingPaidCurrency: "PLN",
    openingPaidSource: "Dane demonstracyjne · potwierdzony zadatek",
    workflowStatus: "Potwierdzona",
    specialRequests: "Dopytać o godzinę przyjazdu i wiek dziecka.",
    createdBy: "Telefon / fallback",
  },
  {
    id: "G003",
    bookingDate: "2026-07-05",
    source: "Airbnb iCal + ręczne szczegóły",
    platform: "Airbnb",
    platformReservationNo: "AIR-HM42Z",
    unitId: "domek-4",
    checkIn: "2026-08-02",
    checkOut: "2026-08-06",
    adults: 2,
    children: 0,
    guestLabel: "Para aktywna - Airbnb",
    cityArea: "Warszawa",
    grossPrice: 2200,
    currency: "PLN",
    paymentStatus: "Opłacone",
    openingPaidAmount: 2200,
    openingPaidCurrency: "PLN",
    openingPaidSource: "Dane demonstracyjne · saldo migracyjne",
    workflowStatus: "Potwierdzona",
    specialRequests: "Pytali o ciszę, rowery i dojście nad stawy.",
    createdBy: "Import Airbnb",
  },
  {
    id: "G004",
    bookingDate: "",
    source: "Telefon / do spięcia z platformą",
    platform: "Telefon",
    unitId: "domek-rybaka",
    checkIn: "2026-08-10",
    checkOut: "2026-08-15",
    adults: 4,
    children: 2,
    guestLabel: "Rodzina 4+2 - do rozpoznania",
    cityArea: "do uzupełnienia",
    paymentStatus: "Do uzupełnienia",
    workflowStatus: "Nowa",
    specialRequests: "Brak danych o motywacji i kanale odkrycia.",
    createdBy: "Telefon",
  },
];

export const initialData: AppData = {
  units,
  bookings: sampleBookings,
  guests: [
    {
      bookingId: "G001",
      groupType: "Rodzina",
      segment: "Rodzina z nastolatkami - wędkarze",
      decisionMaker: "Mama / żona",
      motivation: "Wędkarstwo",
      childrenAges: "ok. 16 i 13",
      jobsLifestyle: "On informatyk, ona zaczyna pracę w szpitalu",
      discoveryChannel: "AI/czat",
      bookingChannel: "Booking",
      searchPhraseOrAiPrompt:
        "miejsce na ryby dla synów; potem sprawdzone na Booking",
      bestQuote: "Mega zadowoleni, siedzą cały czas na rybach",
      objections: "Do dopytania",
      nps: 10,
      satisfaction: 5,
    },
    {
      bookingId: "G002",
      groupType: "Rodzina",
      segment: "Rodzina 2+1 na krótki pobyt",
      decisionMaker: "Do dopytania",
      motivation: "Krótki odpoczynek blisko natury",
      childrenAges: "",
      jobsLifestyle: "",
      discoveryChannel: "Telefon",
      bookingChannel: "Bezpośrednio",
      searchPhraseOrAiPrompt: "",
      bestQuote: "",
      objections: "Do dopytania",
    },
    {
      bookingId: "G003",
      groupType: "Para",
      segment: "Para aktywna / cisza i natura",
      decisionMaker: "Wspólnie",
      motivation: "Cisza, spacer, reset od miasta",
      childrenAges: "",
      jobsLifestyle: "Miejscy profesjonaliści, krótki wyjazd",
      discoveryChannel: "Airbnb",
      bookingChannel: "Airbnb",
      searchPhraseOrAiPrompt: "Airbnb: domek nad wodą, cisza, natura",
      bestQuote: "Szukamy spokojnego miejsca bez tłumów.",
      objections: "Czy w okolicy będzie cicho?",
      nps: 9,
      satisfaction: 4,
    },
  ],
  consents: [
    {
      bookingId: "G001",
      email: "do uzupełnienia",
      marketingConsent: "Do dopytania",
      photoFbConsent: "Tak",
      photoSiteAdsConsent: "Do dopytania",
      consentScope: "Facebook: zdjęcia z rybą",
      consentSource: "rozmowa na miejscu",
    },
    {
      bookingId: "G002",
      email: "brak",
      marketingConsent: "Do dopytania",
      photoFbConsent: "Nie dotyczy",
      photoSiteAdsConsent: "Nie dotyczy",
      consentSource: "brak",
    },
    {
      bookingId: "G003",
      email: "ukryty przez Airbnb",
      marketingConsent: "Nie",
      photoFbConsent: "Do dopytania",
      photoSiteAdsConsent: "Do dopytania",
      consentSource: "Airbnb - brak zgody marketingowej",
    },
  ],
  tasks: [
    {
      id: "TASK001",
      bookingId: "G001",
      type: "Dane",
      priority: "Wysoki",
      status: "Do zrobienia",
      owner: "Patryk",
      unitId: "domek-rybaka",
      title: "Uzupełnić datę rezerwacji, daty pobytu i cenę brutto.",
    },
    {
      id: "TASK002",
      bookingId: "G001",
      type: "Content",
      priority: "Wysoki",
      status: "Do zrobienia",
      owner: "Patryk",
      unitId: "domek-rybaka",
      title: "Sprawdzić zakres zgody na zdjęcia: Facebook, strona, reklama.",
      blocker: "Brak zgody na stronę/reklamę",
    },
    {
      id: "TASK003",
      bookingId: "G001",
      type: "Opinia",
      priority: "Wysoki",
      status: "Do zrobienia",
      owner: "Patryk",
      unitId: "domek-rybaka",
      title: "Poprosić o opinię po pobycie i wybrać najłatwiejszą platformę.",
    },
    {
      id: "TASK004",
      bookingId: "G004",
      type: "Dane",
      priority: "Wysoki",
      status: "Do zrobienia",
      owner: "Patryk",
      unitId: "domek-rybaka",
      title: "Ustalić, skąd trafili i kto decydował o wyborze miejsca.",
    },
    {
      id: "TASK005",
      bookingId: "G003",
      type: "Follow-up",
      priority: "Średni",
      status: "Do zrobienia",
      owner: "Patryk",
      unitId: "domek-4",
      title: "Po pobycie zapytać, czy cisza/natura spełniła oczekiwanie.",
    },
    {
      id: "TASK006",
      bookingId: "G001",
      type: "Sprzątanie",
      priority: "Wysoki",
      status: "Do zrobienia",
      dueDate: "2026-07-17",
      owner: "Pani Ewa",
      unitId: "domek-rybaka",
      title: "Turnover Domku Rybaka po wyjeździe rodziny.",
    },
    {
      id: "TASK007",
      bookingId: "G003",
      type: "Sprzątanie",
      priority: "Średni",
      status: "Do zrobienia",
      dueDate: "2026-08-06",
      owner: "Pani Ewa",
      unitId: "domek-4",
      title: "Sprzątanie Czapli po pobycie Airbnb.",
    },
  ],
  media: [
    {
      id: "MED001",
      bookingId: "G001",
      type: "Zdjęcie",
      caption: "Synowie siedzieli cały dzień na rybach - bardzo zadowoleni.",
      peopleVisible: "dzieci / ryba - dopytać, kto widoczny",
      consentScope: "Facebook OK; strona/reklama do dopytania",
      usageStatus: "Do zgody",
      publishChannel: "Facebook",
      privacyRisk: "Zgoda/RODO",
    },
  ],
  blocks: [
    {
      id: "BLK001",
      unitId: "domek-rybaka",
      dateFrom: "2026-07-25",
      dateTo: "2026-07-26",
      blockType: "Bufor sprzątania",
      reason: "Przykład buforu po długim pobycie.",
      status: "Planowana",
    },
  ],
  rates: [
    {
      id: "RATE001",
      unitId: "domek-rybaka",
      dateFrom: "2026-06-01",
      dateTo: "2026-08-31",
      season: "Wysoki",
      pricePerNight: 650,
      minNights: 3,
      active: true,
    },
    {
      id: "RATE002",
      unitId: "domek-4",
      dateFrom: "2026-06-01",
      dateTo: "2026-08-31",
      season: "Wysoki",
      pricePerNight: 500,
      minNights: 2,
      active: true,
    },
  ],
  costSettings: [],
  imports: [
    {
      id: "IMP001",
      platform: "Booking",
      importedAt: "2026-07-10 09:15",
      syncSource: "API",
      reservationNo: "BKG-19284",
      bookingDate: "2026-07-02",
      guestName: "Rodzina z okolic Gdańska",
      listing: "Domek Rybaka",
      city: "okolice Gdańska",
      checkIn: "2026-07-10",
      checkOut: "2026-07-17",
      adults: 2,
      children: 2,
      childrenAges: "ok. 16 i 13",
      grossPrice: 4550,
      currency: "PLN",
      commission: 682.5,
      payout: 3867.5,
      paymentStatus: "Opłacone",
      specialRequests: "Ryby / wędkarstwo, dopytać o dokładną godzinę przyjazdu.",
      firstMessage: "Szukamy miejsca, gdzie chłopaki będą mogli łowić ryby.",
      dataQuality: "Pełne",
      matchedBookingId: "G001",
      transferStatus: "Przeniesione",
    },
    {
      id: "IMP002",
      platform: "Airbnb",
      importedAt: "2026-07-10 09:18",
      syncSource: "iCal",
      reservationNo: "AIR-HM42Z",
      bookingDate: "2026-07-05",
      guestName: "Para aktywna - Airbnb",
      listing: "Domek 4-osobowy",
      city: "Warszawa",
      checkIn: "2026-08-02",
      checkOut: "2026-08-06",
      adults: 2,
      children: 0,
      grossPrice: 2200,
      currency: "PLN",
      payout: 2134,
      paymentStatus: "Opłacone",
      specialRequests: "Cisza, dojście do stawów, możliwość spacerów.",
      firstMessage: "Czy na miejscu jest spokojnie i czy można spacerować przy wodzie?",
      dataQuality: "Częściowe",
      missingFields: ["prowizja", "zgody marketingowe", "pełny email/telefon"],
      matchedBookingId: "G003",
      transferStatus: "Przeniesione",
    },
    {
      id: "IMP003",
      platform: "Airbnb",
      importedAt: "2026-07-10 09:20",
      syncSource: "CSV/email",
      guestName: "Rezerwacja Airbnb - do sprawdzenia",
      listing: "Domek Rybaka",
      checkIn: "2026-08-18",
      checkOut: "2026-08-21",
      adults: 2,
      children: 2,
      dataQuality: "Minimalne",
      missingFields: ["nr rezerwacji", "cena", "miasto", "wiek dzieci", "pierwsza wiadomość"],
      transferStatus: "Wymaga sprawdzenia",
    },
  ],
  sourceConnections: [
    {
      id: "SRC-BOOKING",
      platform: "Booking",
      connectionType: "iCal",
      status: "Do podłączenia",
      coverage: 0,
      nextStep: "Sprawdzić w Extranecie, czy konto udostępnia adres iCal dla każdego domku.",
      notes: "iCal blokuje terminy, ale nie pobiera ceny, prowizji ani danych gościa.",
      priority: "Teraz",
      staleAfterMinutes: 240,
    },
    {
      id: "SRC-AIRBNB",
      platform: "Airbnb",
      connectionType: "iCal",
      status: "Wymaga sprawdzenia",
      coverage: 0,
      nextStep: "Użyć iCal do dat, a szczegóły uzupełniać z CSV/email/channel managera.",
      notes: "iCal zwykle daje terminy, ale nie pełny profil marketingowy, cenę i zgody.",
      priority: "Teraz",
      staleAfterMinutes: 240,
    },
  ],
  payments: [],
  invoices: [],
  checklistItems: [],
  issues: [],
  messages: [],
  departureDebriefs: [],
  messageTemplates: [],
  automationRules: [],
  scheduledMessages: [],
  marketingTouchpoints: [],
  auditLog: [],
  settings: {
    organizationName: "Stawy u Sikory",
    timezone: "Europe/Warsaw",
    cleaningContactName: "Pani Ewa",
    cleaningPhone: "",
    defaultCheckIn: "16:00",
    defaultCheckOut: "11:00",
    aiApprovalRequired: true,
  },
};
