"use client";

import Link from "next/link";
import { useState } from "react";
import { useAppStore } from "@/components/layout/app-store";
import { Badge, Button, Card, Field, inputClass } from "@/components/ui/primitives";
import { Icon, type IconName } from "@/components/ui/icons";
import { nightsBetween, unitName } from "@/lib/workflow/rules";
import type { InvoiceRecord } from "@/lib/types";
import { todayInPoland } from "@/lib/date";

function money(value: number) { return new Intl.NumberFormat("pl-PL", { style: "currency", currency: "PLN", maximumFractionDigits: 0 }).format(value); }
const monthNames = ["sty","lut","mar","kwi","maj","cze","lip","sie","wrz","paź","lis","gru"];

export function FinancesView() {
  const { data, addInvoice } = useAppStore();
  const years = Array.from(new Set(data.bookings.map((item) => Number(item.checkIn.slice(0,4))).filter(Boolean))).sort((a,b)=>b-a);
  const [year,setYear]=useState(years[0] ?? new Date().getFullYear());
  const [showLedger,setShowLedger]=useState(false);
  const [showAssumptions,setShowAssumptions]=useState(false);
  const [showInvoice,setShowInvoice]=useState(false);
  const bookings = data.bookings.filter((item)=>Number(item.checkIn.slice(0,4))===year && item.workflowStatus!=="Anulowana");
  const payments = data.payments.filter((item)=>Number(item.occurredAt.slice(0,4))===year && item.status==="Zaksięgowana");
  const gross = bookings.reduce((sum,item)=>sum+(item.grossPrice??0),0);
  const commissionFromLedger = payments.filter((item)=>item.type==="Prowizja").reduce((sum,item)=>sum+item.amount,0);
  const commissionFromImports = data.imports.filter((item)=>item.checkIn?.startsWith(String(year))).reduce((sum,item)=>sum+(item.commission??0),0);
  const commission = commissionFromLedger || commissionFromImports;
  const explicitCosts = payments.filter((item)=>item.type==="Koszt").reduce((sum,item)=>sum+item.amount,0);
  const cleaning = explicitCosts || bookings.reduce((sum,item)=>sum+(data.units.find((unit)=>unit.id===item.unitId)?.defaultCleaningCost??0),0);
  const net = gross-commission-cleaning;
  const nights = bookings.reduce((sum,item)=>sum+nightsBetween(item.checkIn,item.checkOut),0);
  const daysInYear = new Date(year,1,29).getMonth()===1?366:365;
  const occupancy = Math.round((nights/Math.max(1,daysInYear*data.units.length))*100);
  const adr = nights?gross/nights:0;
  const revPar = gross/Math.max(1,daysInYear*data.units.length);
  const months = monthNames.map((label,index)=>{const prefix=`${year}-${String(index+1).padStart(2,"0")}`;const revenue=bookings.filter((item)=>item.checkIn.startsWith(prefix)).reduce((sum,item)=>sum+(item.grossPrice??0),0);const monthCosts=data.payments.filter((item)=>item.occurredAt.startsWith(prefix)&&["Prowizja","Koszt","Zwrot"].includes(item.type)&&item.status==="Zaksięgowana").reduce((sum,item)=>sum+item.amount,0);return{label,revenue,net:Math.max(0,revenue-monthCosts)}});
  const maxMonth=Math.max(1,...months.map((item)=>item.revenue));
  const unitRevenue=data.units.map((unit)=>({unit,value:bookings.filter((item)=>item.unitId===unit.id).reduce((sum,item)=>sum+(item.grossPrice??0),0),nights:bookings.filter((item)=>item.unitId===unit.id).reduce((sum,item)=>sum+nightsBetween(item.checkIn,item.checkOut),0)}));
  const maxUnit=Math.max(1,...unitRevenue.map((item)=>item.value));
  const paidByBooking=new Map<string,number>(); payments.filter((item)=>["Wpłata","Zaliczka","Wypłata OTA"].includes(item.type)).forEach((item)=>paidByBooking.set(item.bookingId,(paidByBooking.get(item.bookingId)??0)+item.amount));
  const unsettled=bookings.filter((item)=>item.grossPrice==null || (paidByBooking.get(item.id)??0)<item.grossPrice);

  function exportCsv(){const lines=[["rezerwacja","gość","domek","wartość","zaksięgowano","saldo"],...bookings.map((item)=>{const paid=paidByBooking.get(item.id)??0;return[item.id,item.guestLabel,unitName(data.units,item.unitId),item.grossPrice??0,paid,Math.max(0,(item.grossPrice??0)-paid)]})];const csv=lines.map((line)=>line.map((value)=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`finanse-stawy-os-${year}.csv`;link.click();URL.revokeObjectURL(url);}

  return <div className="grid gap-5">
    <div className="animate-rise-2 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#d9d1c1] bg-[#fffdf8] p-3"><div className="flex items-center gap-2"><span className="text-xs font-black uppercase tracking-[.13em] text-[#7b857f]">Okres</span><select className="min-h-10 rounded-xl border border-[#cec6b7] bg-white px-3 text-sm font-black" value={year} onChange={(event)=>setYear(Number(event.target.value))}>{years.map((item)=><option key={item}>{item}</option>)}</select></div><Button variant="secondary" onClick={exportCsv}><Icon className="size-4" name="download"/>Eksport CSV</Button></div>
    <section className="animate-rise-2 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FinanceStat label="Przychód brutto" value={money(gross)} note={`${bookings.length} aktywnych rezerwacji`} icon="wallet" tone="forest"/><FinanceStat label="Prowizje OTA" value={money(commission)} note={commission?`${Math.round((commission/Math.max(1,gross))*100)}% przychodu`:"brak transakcji prowizji"} icon="plug" tone="coral"/><FinanceStat label="Koszty operacyjne" value={money(cleaning)} note={explicitCosts?"z rejestru transakcji":"szacunek sprzątania"} icon="cleaning" tone="sun"/><FinanceStat label="Wynik operacyjny" value={money(net)} note="przed podatkami i mediami" icon="spark" tone="lake"/></section>
    <section className="grid gap-3 sm:grid-cols-3"><Mini label="Obłożenie" value={`${occupancy}%`} note={`${nights} sprzedanych nocy`}/><Mini label="ADR" value={money(adr)} note="średnia cena sprzedanej nocy"/><Mini label="RevPAR" value={money(revPar)} note="przychód na dostępną noc"/></section>

    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="overflow-hidden"><div className="border-b border-[#e2dbce] p-5 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Przepływ pieniędzy</p><h2 className="font-display text-2xl font-semibold">Przychód i wynik miesięczny</h2></div><div className="p-5 sm:p-6"><div className="flex h-64 items-end gap-2 border-b border-[#dcd5c8] px-1">{months.map((item)=><div className="group flex h-full flex-1 flex-col justify-end gap-2" key={item.label}><div className="relative mx-auto w-full max-w-10 rounded-t-lg bg-[#dfe6d5]" style={{height:`${Math.max(item.revenue?6:0,(item.revenue/maxMonth)*100)}%`}} title={`${item.label}: ${money(item.revenue)}`}><div className="absolute inset-x-0 bottom-0 rounded-t-lg bg-[#3b7d67]" style={{height:`${item.revenue?Math.max(0,(item.net/item.revenue)*100):0}%`}}/></div><span className="text-center text-[9px] font-black uppercase text-[#818a85]">{item.label}</span></div>)}</div><div className="mt-5 flex gap-4 text-xs font-bold text-[#65736c]"><span className="inline-flex items-center gap-2"><span className="size-2.5 rounded-full bg-[#3b7d67]"/>Wynik</span><span className="inline-flex items-center gap-2"><span className="size-2.5 rounded-full bg-[#dfe6d5]"/>Przychód</span></div></div></Card>
      <Card className="overflow-hidden"><div className="border-b border-[#e2dbce] p-5 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Do działania</p><h2 className="font-display text-2xl font-semibold">Salda rezerwacji</h2></div><div className="grid gap-2 p-3">{unsettled.slice(0,6).map((booking)=>{const paid=paidByBooking.get(booking.id)??0;return <Link className="flex items-center gap-3 rounded-2xl p-3 transition hover:bg-[#f3f0e8]" href={`/bookings/${booking.id}`} key={booking.id}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#f7ebc9] text-[#806118]"><Icon className="size-5" name="wallet"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{booking.guestLabel}</p><p className="text-xs text-[#6d7972]">{unitName(data.units,booking.unitId)} · wpłacono {money(paid)}</p></div><div className="text-right"><p className="font-display text-base font-semibold">{booking.grossPrice==null?"—":money(Math.max(0,booking.grossPrice-paid))}</p><Badge tone={booking.grossPrice==null?"bad":"warn"}>{booking.grossPrice==null?"brak ceny":"do rozliczenia"}</Badge></div></Link>})}{!unsettled.length?<p className="p-8 text-center text-sm font-bold text-[#68756f]">Wszystkie salda wynoszą zero.</p>:null}</div><div className="border-t border-[#e2dbce] p-4"><Button className="w-full" variant="secondary" onClick={()=>setShowLedger((value)=>!value)}>{showLedger?"Ukryj rejestr":"Otwórz pełny rejestr"}</Button></div></Card>
    </div>

    {showLedger?<Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-display text-2xl font-semibold">Rejestr transakcji {year}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#f3f0e8] text-[10px] font-black uppercase tracking-[.13em]"><tr><th className="p-4">Data</th><th>Rezerwacja</th><th>Typ</th><th>Status</th><th className="pr-4 text-right">Kwota</th></tr></thead><tbody>{payments.map((item)=><tr className="border-t" key={item.id}><td className="p-4">{item.occurredAt}</td><td>{item.bookingId}</td><td>{item.type}</td><td><Badge tone="good">{item.status}</Badge></td><td className="pr-4 text-right font-black">{money(item.amount)}</td></tr>)}{!payments.length?<tr><td className="p-8 text-center text-[#68756f]" colSpan={5}>Brak zaksięgowanych transakcji w wybranym roku.</td></tr>:null}</tbody></table></div></Card>:null}

    <Card className="overflow-hidden"><div className="flex items-start justify-between gap-3 border-b p-5"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Dokumenty sprzedaży</p><h2 className="font-display text-2xl font-semibold">Rejestr faktur i rachunków</h2><p className="mt-1 text-xs text-[#68756f]">Rejestr operacyjny — nie zastępuje KSeF ani programu księgowego.</p></div><Button variant="secondary" onClick={()=>setShowInvoice(true)}><Icon className="size-4" name="plus"/>Dodaj dokument</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#f3f0e8] text-[10px] font-black uppercase tracking-[.13em]"><tr><th className="p-4">Numer</th><th>Data</th><th>Rezerwacja</th><th>Status</th><th className="pr-4 text-right">Kwota</th></tr></thead><tbody>{data.invoices.filter((item)=>item.issuedAt.startsWith(String(year))).map((item)=><tr className="border-t" key={item.id}><td className="p-4 font-black">{item.number}</td><td>{item.issuedAt}</td><td>{item.bookingId??"—"}</td><td><Badge tone={item.status==="Opłacona"?"good":"neutral"}>{item.status}</Badge></td><td className="pr-4 text-right font-black">{money(item.amount)}</td></tr>)}{!data.invoices.some((item)=>item.issuedAt.startsWith(String(year)))?<tr><td className="p-8 text-center text-[#68756f]" colSpan={5}>Brak dokumentów w wybranym roku.</td></tr>:null}</tbody></table></div></Card>

    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Card className="p-5 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Rentowność domków</p><h2 className="font-display text-2xl font-semibold">Przychód według obiektu</h2><div className="mt-5 grid gap-4">{unitRevenue.map(({unit,value,nights:unitNights})=><div key={unit.id}><div className="mb-2 flex items-end justify-between"><div><p className="text-sm font-black">{unit.name}</p><p className="text-xs text-[#6d7972]">{unitNights} sprzedanych nocy</p></div><p className="font-display text-xl font-semibold">{money(value)}</p></div><div className="h-2 overflow-hidden rounded-full bg-[#e9e4da]"><div className="h-full rounded-full bg-[#4a8269]" style={{width:`${(value/maxUnit)*100}%`}}/></div></div>)}</div></Card><Card className="bg-[#edf1e4] p-5 sm:p-6"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#174d3b] text-white"><Icon className="size-6" name="spark"/></span><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#6f7d48]">Doradca — wymaga zatwierdzenia</p><h2 className="mt-1 font-display text-2xl font-semibold">Kanał direct może ograniczyć prowizje.</h2><p className="mt-2 text-sm leading-6 text-[#5e6d65]">W danych za {year} zapisano {money(commission)} prowizji. Rekomendacja ma charakter informacyjny i nie zmieni cen ani nie wyśle kampanii.</p><Button className="mt-4" variant="secondary" onClick={()=>setShowAssumptions((value)=>!value)}>{showAssumptions?"Ukryj założenia":"Pokaż założenia"}</Button>{showAssumptions?<p className="mt-3 rounded-xl bg-white/70 p-3 text-xs leading-5 text-[#5e6d65]">Wyliczenie wykorzystuje wyłącznie zaksięgowane prowizje, a gdy ich nie ma — wartości zaimportowane z OTA. Nie zakłada automatycznie prowizji dla brakujących rekordów.</p>:null}</div></div></Card></div>
    {showInvoice?<InvoiceDialog bookings={bookings} onClose={()=>setShowInvoice(false)} onSave={(invoice)=>{addInvoice(invoice);setShowInvoice(false);}}/>:null}
  </div>;
}

function Mini({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-2xl border border-[#d9d1c1] bg-[#fffdf8] p-4"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#7b857f]">{label}</p><p className="mt-1 font-display text-2xl font-semibold">{value}</p><p className="text-xs text-[#707b75]">{note}</p></div>}
function FinanceStat({label,value,note,icon,tone}:{label:string;value:string;note:string;icon:IconName;tone:"forest"|"coral"|"sun"|"lake"}){const tones={forest:"bg-[#174d3b] text-white",coral:"bg-[#f7dfd7] text-[#a1442c]",sun:"bg-[#f6ebc8] text-[#806117]",lake:"bg-[#dcebea] text-[#276662]"};return <div className="rounded-[18px] border border-[#d9d1c1] bg-[#fffdf8] p-4"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#7b857f]">{label}</p><p className="mt-2 font-display text-[28px] font-semibold">{value}</p><p className="mt-1 text-xs text-[#707b75]">{note}</p></div><span className={`grid size-10 place-items-center rounded-xl ${tones[tone]}`}><Icon className="size-5" name={icon}/></span></div></div>}
function InvoiceDialog({bookings,onClose,onSave}:{bookings:ReturnType<typeof useAppStore>["data"]["bookings"];onClose:()=>void;onSave:(invoice:InvoiceRecord)=>void}){const [form,setForm]=useState({bookingId:bookings[0]?.id??"",number:`FV/${todayInPoland().replaceAll("-","")}/1`,issuedAt:todayInPoland(),amount:bookings[0]?.grossPrice?String(bookings[0].grossPrice):"",status:"Do wystawienia" as InvoiceRecord["status"]});return <div className="fixed inset-0 z-50 grid place-items-center bg-[#102c24]/70 p-4 backdrop-blur-sm" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><form className="w-full max-w-lg rounded-[22px] bg-[#fffdf8] p-6 shadow-2xl" onSubmit={(event)=>{event.preventDefault();const amount=Number(form.amount);if(!amount)return;onSave({id:`INV-${Date.now()}`,...form,amount});}}><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Rejestr dokumentów</p><h2 className="font-display text-2xl font-semibold">Dodaj fakturę lub rachunek</h2></div><button aria-label="Zamknij" type="button" onClick={onClose}><Icon className="size-5" name="close"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Numer"><input className={inputClass} required value={form.number} onChange={(event)=>setForm({...form,number:event.target.value})}/></Field><Field label="Data"><input className={inputClass} type="date" required value={form.issuedAt} onChange={(event)=>setForm({...form,issuedAt:event.target.value})}/></Field><Field label="Rezerwacja"><select className={inputClass} value={form.bookingId} onChange={(event)=>{const booking=bookings.find((item)=>item.id===event.target.value);setForm({...form,bookingId:event.target.value,amount:booking?.grossPrice?String(booking.grossPrice):form.amount});}}>{bookings.map((booking)=><option key={booking.id} value={booking.id}>{booking.guestLabel}</option>)}</select></Field><Field label="Kwota PLN"><input className={inputClass} min="0.01" step="0.01" type="number" required value={form.amount} onChange={(event)=>setForm({...form,amount:event.target.value})}/></Field><Field label="Status"><select className={inputClass} value={form.status} onChange={(event)=>setForm({...form,status:event.target.value as InvoiceRecord["status"]})}>{["Do wystawienia","Wystawiona","Opłacona","Anulowana"].map((item)=><option key={item}>{item}</option>)}</select></Field></div><p className="mt-4 rounded-xl bg-[#f5ead0] p-3 text-xs leading-5 text-[#725a1d]">Ten wpis jest rejestrem operacyjnym. Nie wysyła dokumentu do KSeF i nie nadaje mu skutków księgowych.</p><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Anuluj</Button><Button type="submit">Dodaj do rejestru</Button></div></form></div>}
