"use client";

import { useState } from "react";
import { useAppStore } from "@/components/layout/app-store";
import { Badge, Button, Card, Field, inputClass } from "@/components/ui/primitives";
import { Icon, type IconName } from "@/components/ui/icons";
import { PricingSettings } from "@/components/settings/pricing-settings";
import { formatPolishCount } from "@/lib/polish-plural";

export function SettingsView() {
  const { data, dataStatus, syncMode, updateSettings, exportSnapshot, resetDemo } = useAppStore();
  const [form,setForm]=useState(data.settings);
  const [saved,setSaved]=useState(false);
  function save(){if(dataStatus!=="ready")return;updateSettings(form);setSaved(true);window.setTimeout(()=>setSaved(false),2500);}
  return <div className="grid gap-5">
    <section className="animate-rise-2 grid gap-4 sm:grid-cols-3"><SettingStat icon="home" label="Domki" value={data.units.length}/><SettingStat icon="people" label="Dostęp" value="Właściciele"/><SettingStat icon="refresh" label="Magazyn danych" value={syncMode==="cloud"?"Chmura":"Lokalny"}/></section>
    {saved?<p aria-live="polite" className="rounded-xl bg-[#dfeede] p-3 text-sm font-bold text-[#215c3b]">Ustawienia zostały zapisane.</p>:null}
    <div className="animate-rise-3 grid gap-5 xl:grid-cols-[1fr_380px]">
      <div className="grid gap-5">
        <Card className="overflow-hidden"><Title eyebrow="Operacje" title="Kontakt i godziny"/><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Nazwa obiektu"><input className={inputClass} value={form.organizationName} onChange={(event)=>setForm({...form,organizationName:event.target.value})}/></Field><Field label="Osoba sprzątająca"><input className={inputClass} value={form.cleaningContactName} onChange={(event)=>setForm({...form,cleaningContactName:event.target.value})}/></Field><Field label="Telefon do SMS"><input className={inputClass} inputMode="tel" placeholder="+48 600 000 000" value={form.cleaningPhone} onChange={(event)=>setForm({...form,cleaningPhone:event.target.value})}/></Field><Field label="Strefa czasowa"><input className={inputClass} disabled value={form.timezone}/></Field><Field label="Domyślny check-in"><input className={inputClass} type="time" value={form.defaultCheckIn} onChange={(event)=>setForm({...form,defaultCheckIn:event.target.value})}/></Field><Field label="Domyślny check-out"><input className={inputClass} type="time" value={form.defaultCheckOut} onChange={(event)=>setForm({...form,defaultCheckOut:event.target.value})}/></Field></div><div className="flex justify-end border-t p-4"><Button disabled={dataStatus!=="ready"} onClick={save}>Zapisz ustawienia</Button></div></Card>
        <PricingSettings/>
        <Card className="overflow-hidden"><Title eyebrow="Automatyzacje" title="Reguły draft-first"/><div className="grid gap-2 p-3">{data.automationRules.map((rule)=><Rule key={rule.id} icon="message" title={rule.name} body={`${rule.trigger} · ${rule.offsetDays === 0 ? "tego samego dnia" : `${formatPolishCount(Math.abs(rule.offsetDays), "dzień", "dni", "dni")} ${rule.offsetDays < 0 ? "wcześniej" : "później"}`} · ${rule.sendTime}`} active={rule.active}/>)}</div><div className="border-t border-[#e2dbce] p-4 text-xs leading-5 text-[#68756f]">Wszystkie reguły tworzą szkice. Wysyłka automatyczna pozostaje zablokowana, dopóki kanał i zgody nie przejdą testów.</div></Card>
        <Card className="overflow-hidden"><Title eyebrow="Komunikacja" title="Biblioteka szablonów"/><div className="grid gap-2 p-3 sm:grid-cols-2">{data.messageTemplates.map((template)=><article className="rounded-2xl border border-[#ded7ca] bg-white p-4" key={template.id}><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-black">{template.name}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.11em] text-[#758079]">{template.purpose} · {template.channel}</p></div><Badge tone={template.active?"good":"neutral"}>v{template.version}</Badge></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-[#65736c]">{template.body}</p><p className="mt-3 text-[10px] font-semibold text-[#838b86]">{template.allowedVariables.length} dozwolonych zmiennych · {template.language.toUpperCase()}</p></article>)}</div></Card>
      </div>
      <aside className="grid content-start gap-5">
        <Card className="p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Dane i backup</p><h2 className="font-display text-xl font-semibold">Bezpieczeństwo operacyjne</h2><div className="mt-4 grid gap-3"><Check text={syncMode==="cloud"?"Synchronizacja wielourządzeniowa aktywna":syncMode==="conflict"?"Konflikt zmian — odśwież aplikację":"Tryb lokalny — skonfiguruj Supabase"}/><Check text="Historia zmian w aplikacji"/><Check text="Import Mobile-Calendar bez usuwania danych"/><Check text="Prywatne linki kalendarza"/></div><Button className="mt-5 w-full" variant="secondary" onClick={exportSnapshot}><Icon className="size-4" name="download"/>Pobierz zaszyfrowany backup</Button></Card>
        <Card className="p-5"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#e2ecde] text-[#376448]"><Icon className="size-5" name="spark"/></span><div><p className="text-sm font-black">Stawy AI</p><p className="mt-1 text-xs leading-5 text-[#68756f]">Rekomendacje nie mogą wysłać wiadomości ani zmienić ceny bez zatwierdzenia właściciela.</p></div></div><label className="mt-4 flex items-center justify-between rounded-xl bg-[#f2efe7] p-3"><span className="text-xs font-black">Wymagaj zatwierdzenia</span><input checked={form.aiApprovalRequired} className="size-5 accent-[#174d3b]" type="checkbox" onChange={(event)=>setForm({...form,aiApprovalRequired:event.target.checked})}/></label></Card>
        {process.env.NODE_ENV!=="production"?<Card className="p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">Tylko development</p><h2 className="font-display text-xl font-semibold">Dane demonstracyjne</h2><p className="mt-2 text-xs leading-5 text-[#68756f]">Reset jest ukryty w buildzie produkcyjnym. Przed użyciem pobierz backup.</p><Button className="mt-4 w-full" variant="danger" onClick={()=>{if(window.confirm("Przywrócić dane demo? Lokalne zmiany zostaną nadpisane."))resetDemo();}}><Icon className="size-4" name="refresh"/>Przywróć demo</Button></Card>:null}
      </aside>
    </div>
  </div>;
}

function SettingStat({icon,label,value}:{icon:IconName;label:string;value:string|number}){return <div className="flex items-center gap-4 rounded-[18px] border border-[#d9d1c1] bg-[#fffdf8] p-4"><span className="grid size-11 place-items-center rounded-xl bg-[#e5ecdf] text-[#3f674c]"><Icon className="size-5" name={icon}/></span><div><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#7b857f]">{label}</p><p className="font-display text-2xl font-semibold">{value}</p></div></div>}
function Title({eyebrow,title}:{eyebrow:string;title:string}){return <div className="border-b border-[#e2dbce] p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#7d8b4d]">{eyebrow}</p><h2 className="font-display text-2xl font-semibold">{title}</h2></div>}
function Rule({icon,title,body,active=false}:{icon:IconName;title:string;body:string;active?:boolean}){return <div className="flex items-center gap-3 rounded-2xl p-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#e6ece0] text-[#42664e]"><Icon className="size-[18px]" name={icon}/></span><div className="flex-1"><p className="text-sm font-black">{title}</p><p className="text-xs text-[#6b7771]">{body}</p></div><Badge tone={active?"good":"neutral"}>{active?"Aktywna":"Wyłączona"}</Badge></div>}
function Check({text}:{text:string}){return <div className="flex items-center gap-2.5 text-xs font-bold text-[#50635a]"><span className="grid size-5 place-items-center rounded-full bg-[#dfeede] text-[#2f6848]"><Icon className="size-3" name="check"/></span>{text}</div>}
